# Generated by Django 5.1.6 on 2025-02-24 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='IncomingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, help_text="If item doesn't exist in inventory, enter name here", max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numOrdered', models.PositiveIntegerField()),
                ('orderedBy', models.CharField(max_length=30)),
                ('orderedOn', models.DateTimeField(auto_now_add=True)),
                ('expectedDelivery', models.DateTimeField(blank=True, null=True)),
                ('wasDelivered', models.BooleanField(default=False)),
                ('deliveredOn', models.DateTimeField(blank=True, null=True)),
                ('receivedBy', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True, max_length=255, null=True)),
                ('invoiceNumber', models.CharField(blank=True, max_length=50, unique=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_orders', to='api.inventoryitem')),
            ],
            options={
                'ordering': ['-orderedOn'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('num_ordered', models.PositiveIntegerField()),
                ('ordered_by', models.CharField(blank=True, max_length=200, null=True)),
                ('ordered_on', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrier', models.CharField(max_length=30)),
                ('has_shipped', models.BooleanField(default=False)),
                ('shipped_on', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.inventoryitem')),
            ],
            options={
                'ordering': ['-ordered_on'],
            },
        ),
    ]
